### ISSUE TITLE
NuGet dlls not copied over to the build folder

### ISSUE THREAD

**Issue by adecler** [BHoM/template-repository#23]
#### Description:
Dlls from NuGet packages are not copied by default with net standard 2.0.
We need to add `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in the `<PropertyGroup>` of the project files to fix that.

#### Steps to reproduce:
You can use the [PowerPoint_Toolkit repo](https://github.com/BHoM/PowerPoint_Toolkit) to test the behaviour. You will need to remove the line mentioned above from the adapter project (and clean the build folder obviously) to see that it stops copying the dlls from the NuGet packages.

**Comment by FraserGreenroyd** [comment]
Makes sense and would be good to implement, happy for you or @alelom to handle @adecler and then I'll play reviewer role 😄

**Comment by alelom** [comment]
Thanks for this @adecler @FraserGreenroyd .
